<?php
/**
 * ProviderSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EasyAppointmentsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * easyappointments-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EasyAppointmentsClient;

/**
 * ProviderSettingsTest Class Doc Comment
 *
 * @category    Class
 * @description ProviderSettings
 * @package     EasyAppointmentsClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProviderSettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProviderSettings"
     */
    public function testProviderSettings()
    {
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }

    /**
     * Test attribute "notifications"
     */
    public function testPropertyNotifications()
    {
    }

    /**
     * Test attribute "calendar_view"
     */
    public function testPropertyCalendarView()
    {
    }

    /**
     * Test attribute "google_sync"
     */
    public function testPropertyGoogleSync()
    {
    }

    /**
     * Test attribute "google_calendar"
     */
    public function testPropertyGoogleCalendar()
    {
    }

    /**
     * Test attribute "google_token"
     */
    public function testPropertyGoogleToken()
    {
    }

    /**
     * Test attribute "sync_future_days"
     */
    public function testPropertySyncFutureDays()
    {
    }

    /**
     * Test attribute "sync_past_days"
     */
    public function testPropertySyncPastDays()
    {
    }

    /**
     * Test attribute "working_plan"
     */
    public function testPropertyWorkingPlan()
    {
    }
}
