<?php
/**
 * AppointmentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EasyAppointmentsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * easyappointments-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EasyAppointmentsClient;

use \EasyAppointmentsClient\Configuration;
use \EasyAppointmentsClient\ApiException;
use \EasyAppointmentsClient\ObjectSerializer;

/**
 * AppointmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  EasyAppointmentsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AppointmentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for appointmentsAppointmentIdDelete
     *
     * Delete single appointment.
     *
     */
    public function testAppointmentsAppointmentIdDelete()
    {
    }

    /**
     * Test case for appointmentsAppointmentIdGet
     *
     * Get single appointment.
     *
     */
    public function testAppointmentsAppointmentIdGet()
    {
    }

    /**
     * Test case for appointmentsAppointmentIdPut
     *
     * Update single appointment.
     *
     */
    public function testAppointmentsAppointmentIdPut()
    {
    }

    /**
     * Test case for appointmentsGet
     *
     * Get all appointments.
     *
     */
    public function testAppointmentsGet()
    {
    }

    /**
     * Test case for appointmentsPost
     *
     * Create single appointment.
     *
     */
    public function testAppointmentsPost()
    {
    }
}
