<?php
/**
 * CategoriesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EasyAppointmentsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * easyappointments-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EasyAppointmentsClient;

use \EasyAppointmentsClient\Configuration;
use \EasyAppointmentsClient\ApiException;
use \EasyAppointmentsClient\ObjectSerializer;

/**
 * CategoriesApiTest Class Doc Comment
 *
 * @category Class
 * @package  EasyAppointmentsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CategoriesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for categoriesCategoryIdDelete
     *
     * Delete single category.
     *
     */
    public function testCategoriesCategoryIdDelete()
    {
    }

    /**
     * Test case for categoriesCategoryIdGet
     *
     * Get single category.
     *
     */
    public function testCategoriesCategoryIdGet()
    {
    }

    /**
     * Test case for categoriesCategoryIdPut
     *
     * Update single category.
     *
     */
    public function testCategoriesCategoryIdPut()
    {
    }

    /**
     * Test case for categoriesGet
     *
     * Get all categories.
     *
     */
    public function testCategoriesGet()
    {
    }

    /**
     * Test case for categoriesPost
     *
     * Create single category.
     *
     */
    public function testCategoriesPost()
    {
    }
}
