<?php
/**
 * ProvidersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EasyAppointmentsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * easyappointments-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EasyAppointmentsClient;

use \EasyAppointmentsClient\Configuration;
use \EasyAppointmentsClient\ApiException;
use \EasyAppointmentsClient\ObjectSerializer;

/**
 * ProvidersApiTest Class Doc Comment
 *
 * @category Class
 * @package  EasyAppointmentsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProvidersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for providersGet
     *
     * Get all providers.
     *
     */
    public function testProvidersGet()
    {
    }

    /**
     * Test case for providersPost
     *
     * Create single provider.
     *
     */
    public function testProvidersPost()
    {
    }

    /**
     * Test case for providersProviderIdDelete
     *
     * Delete single provider.
     *
     */
    public function testProvidersProviderIdDelete()
    {
    }

    /**
     * Test case for providersProviderIdGet
     *
     * Get single provider.
     *
     */
    public function testProvidersProviderIdGet()
    {
    }

    /**
     * Test case for providersProviderIdPut
     *
     * Update single provider.
     *
     */
    public function testProvidersProviderIdPut()
    {
    }
}
