<?php
/**
 * SecretariesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EasyAppointmentsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * easyappointments-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EasyAppointmentsClient;

use \EasyAppointmentsClient\Configuration;
use \EasyAppointmentsClient\ApiException;
use \EasyAppointmentsClient\ObjectSerializer;

/**
 * SecretariesApiTest Class Doc Comment
 *
 * @category Class
 * @package  EasyAppointmentsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SecretariesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for secretariesGet
     *
     * Get all secretaries.
     *
     */
    public function testSecretariesGet()
    {
    }

    /**
     * Test case for secretariesPost
     *
     * Create single secretary.
     *
     */
    public function testSecretariesPost()
    {
    }

    /**
     * Test case for secretariesSecretaryIdDelete
     *
     * Delete single secretary.
     *
     */
    public function testSecretariesSecretaryIdDelete()
    {
    }

    /**
     * Test case for secretariesSecretaryIdGet
     *
     * Get single secretary.
     *
     */
    public function testSecretariesSecretaryIdGet()
    {
    }

    /**
     * Test case for secretariesSecretaryIdPut
     *
     * Update single secretary.
     *
     */
    public function testSecretariesSecretaryIdPut()
    {
    }
}
