<?php
/**
 * UnavailabilitiesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EasyAppointmentsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * easyappointments-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EasyAppointmentsClient;

use \EasyAppointmentsClient\Configuration;
use \EasyAppointmentsClient\ApiException;
use \EasyAppointmentsClient\ObjectSerializer;

/**
 * UnavailabilitiesApiTest Class Doc Comment
 *
 * @category Class
 * @package  EasyAppointmentsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UnavailabilitiesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for unavailabilitiesGet
     *
     * Get all unavailabilities.
     *
     */
    public function testUnavailabilitiesGet()
    {
    }

    /**
     * Test case for unavailabilitiesPost
     *
     * Create single unavailability.
     *
     */
    public function testUnavailabilitiesPost()
    {
    }

    /**
     * Test case for unavailabilitiesUnavailabilityIdDelete
     *
     * Delete single unavailability.
     *
     */
    public function testUnavailabilitiesUnavailabilityIdDelete()
    {
    }

    /**
     * Test case for unavailabilitiesUnavailabilityIdGet
     *
     * Get single unavailability.
     *
     */
    public function testUnavailabilitiesUnavailabilityIdGet()
    {
    }

    /**
     * Test case for unavailabilitiesUnavailabilityIdPut
     *
     * Update single unavailability.
     *
     */
    public function testUnavailabilitiesUnavailabilityIdPut()
    {
    }
}
